she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('search/', views.SearchFeature.as_view(), name='searchView'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views

app_name ='users'
urlpatterns = [    
    path('create-account/', views.CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/', views.AccountView.as_view(), name='user'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(       
        get_user_model(),
        on_delete = models.CASCADE
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    image = models.URLField(max_length=200,default='https://picsum.photos/600')

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        if AbstractUser.get_full_name(self) != '':
            name = AbstractUser.get_full_name(self)
        else:
            name = self.username
        return name

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ["title","image", "content"]

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:        
      model = CustomUser        
      fields = ['username', 'email', 'first_name', 'last_name']

class CustomUserChangeForm(UserChangeForm):
  class Meta:        
    model = CustomUser        
    fields = ['username', 'email']

she_codes_news/news/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.db.models import Q
from users.models import CustomUser
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import NewsStory
from .forms import StoryForm, CommentForm

class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by("-pub_date")[:4]
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

@method_decorator(login_required, name='dispatch')
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index') # change this to take to new story page

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class SearchFeature(generic.ListView):
    model = NewsStory
    template_name = 'news/searchStory.html'
    context_object_name = 'searchView'

    def post(self,request):
        search_query = request.POST['article_search']
        search_results =  NewsStory.objects.filter(Q(title__icontains=search_query) | Q(content__icontains=search_query))
        for user in CustomUser.objects.all():
            if search_query.lower() in str(user).lower():
                search_results |= NewsStory.objects.filter(author__username__icontains=user.username)
            else:
                pass
        return render(request, 'news/searchStory.html', {'query': search_query,'search_results':search_results})

she_codes_news/users/views.py
from typing import Any, Dict
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm
from news.models import NewsStory
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "users/createAccount.html"

@method_decorator(login_required, name='dispatch')
class AccountView(generic.DetailView):
    form_class = CustomUser
    context_object_name = 'user'
    template_name = 'users/account.html'

    def get_queryset(self):
        '''Return all user attributes.'''
        return CustomUser.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stories_by_author'] = NewsStory.objects.filter(author_id = self.request.user.id).order_by("-pub_date")
        return context

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% block content %}
    <form action="" method="post">        
        {% csrf_token %}        
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %} 
{% load static %} 

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock %} 

{% block content %}
<form method="post" action="{% url 'news:searchView' %}">
  {% csrf_token %}
  <input
    type="search"
    placeholder="Search"
    name="article_search"
    aria-label="Search" />
  <button class="btn btn-outline-success" type="submit">Search</button>
</form>

<h2>Latest News</h2>

<div id="latest-stories">
  {% if latest_stories %} 
    {% for story in latest_stories %} 
        {% include "./storyCard.html" with story=story position=forloop.counter %} 
    {% endfor %}
  {% else %}
    <p>No stories are available.</p>
  {% endif %}
</div>

<div id="all-stories">
  {% if latest_stories %} 
    {% for story in all_stories %} 
        {% include "./storyCard.html" with story=story %} 
    {% endfor %} 
  {% else %}
    <p>No stories are available.</p>
  {% endif %}
</div>
{% endblock %}

she_codes_news/news/templates/news/searchStory.html
{% extends "base.html" %} 
{% load static %} 

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock %} 

{% block content %}
<form method="post" action="{% url 'news:searchView' %}">
  {% csrf_token %}
  <input
    type="search"
    placeholder="Search"
    name="article_search"
    aria-label="Search" />
  <button class="btn btn-outline-success" type="submit">Search</button>
</form>
<div>
  {% csrf_token %} 
  {% if query %} 
    {% for story in search_results %} 
        {% include "./storyCard.html" with story=story %} 
    {% endfor %} 
  {% else %}
    <h3>No search results found</h3>
  {% endif %}
</div>
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src={{ story.image }}>
        {{ story.content|linebreaks }}
    </div>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        <img src={{ story.image }}>
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Rosie Maguire">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
  <a href="{% url 'news:index' %}">Home</a>
  {% if request.user.is_authenticated %}
    {% if user.first_name == '' %}
      <a href="{% url 'users:user' user.id %}">{{ user.username }}</a>
    {% else %}
      <a href="{% url 'users:user' user.id %}">{{ user.first_name }}</a>
    {% endif %} 
    <a href="{% url 'news:newStory' %}">Write Story</a>
    <a href="{% url 'logout' %}">Logout</a>
  {% else %}
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'users:createAccount' %}">Create Account</a>
  {% endif %}
</nav>

she_codes_news/users/templates/users/account.html
{% extends "base.html" %} 
{% load static %} 

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static '/news/styles.css' %}" />
{% endblock %} 

{% block content %}
<section id="user-details">
  <h2>My Account</h2>
  <p>Username: {{ user.username }}</p>
  <p>First Name: {{ user.first_name }}</p>
  <p>Last Name: {{ user.last_name }}</p>
  <p>Email: {{ user.email }}</p>
  <p>Last Login: {{ user.last_login}}</p>
<div id="stories-by-author">
    <h2>My articles</h2>
<article id="my-articles">

    {% if stories_by_author %} 
        {% for story in stories_by_author %} 
            {% include "./../news/storyCard.html" with story=story %}
        {% endfor %} 
    {% else %}
    <p>You have not written any stories.</p>
    {% endif %}
</article>
</div>
</section>
<footer>
  <a href="{% url 'password_change' %}">Change Password</a>
  <a href="#">Update my details</a>
</footer>
{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %} 

{% block content %}
  <h2>Create Account</h2>
  <form method="post">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">Create Account</button>
  </form>
{% endblock %}